#include <stdio.h>
#include <fcntl.h>
#include <io.h>
#include <string.h>

char *cHdr = "/* Font %s: generated by fnt2c %s */\r\n\r\n";
char *sHdr = "static font_t FONT_NAME = {\r\n";
char *sRec = "{ 0x%02X, 0x%02X, 0x%02X, 0x%02X, 0x%02X, 0x%02X, 0x%02X, 0x%02X },\r\n";
char *sEnd = "};\r\n\r\n";
char *cEnd = "/* End */\r\n";

char *version = "$Revision:   1.1  $";

void main(int argc, char **argv)
{
int ff, cf, n;
unsigned char fb[8];
char buf[128];

/* check args */
   if(argc < 3)
   {
      puts("usage: fnt2c <font file> <C file>");
      return;
   }

/* open files */
   ff = open(argv[1], O_RDONLY | O_BINARY);
   cf = open(argv[2], O_WRONLY | O_TRUNC | O_BINARY | O_CREAT, 0666);
   if(ff < 0 || cf < 0)
   {
      fprintf(stderr, "Unable to open file(s) %s & %s\n", argv[1], argv[2]);
      return;
   }

/* parse font name from file name */
   for(n=0; argv[1][n] && argv[1][n] != '.'; n++);
   if(argv[1][n])
      argv[1][n] = 0;

/* generate C file header & structure header */
   write(cf, buf, sprintf(buf, cHdr, argv[1], version));
   write(cf, sHdr, strlen(sHdr));

/* read each bitmap (8 byte string) and write a C structure entry */
   do
   {
      n = read(ff, fb, 8);
      switch(n)
      {
      case -1:
         perror("Reading font file: ");
         return;
      case 0:
         continue;
      case 8:
         write(cf, buf, sprintf(buf, sRec, fb[0], fb[1], fb[2], fb[3], fb[4], fb[5], fb[6], fb[7]));
         break;
      }
   } while(n > 0);
   write(cf, sEnd, strlen(sEnd));
   
/* write c end marker */
   write(cf, cEnd, strlen(cEnd));
   close(ff);
   close(cf);
}

